### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by ghost** [JMSDOnline/vstacklet#82]
I am testing this script with Ubuntu 16.04 fresh install.
I have tested the script with php 5 and 7, a total of 4 times and I get the same error each time.

```
Apr 29 17:14:11 testbox nginx[28690]: nginx: [emerg] BIO_new_file("/srv/www/no/ssl/sitename.crt") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/srv/www/no/ssl/sitename.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)
Apr 29 17:14:11 testbox nginx[28690]: nginx: configuration file /etc/nginx/nginx.conf test failed
```

I was not able to find sitename.crt anywhere on the system.

Thanks

**Comment by JMSDOnline** [comment]
It looks like the script didn't print your site name to the cert. 
Have you verified that that it created (for instance) `no.crt` within `/srv/www/no/ssl/`

I am going to be replacing the standard SSL function with LetsEncrypt within the next week. All this function does (other than generating a self-signed certificate) is uncomments the ssl includes within the /etc/nginx/conf.d/yoursite.conf file.

Additionally, this error should not make noise if you are foregoing the install of SSL on initial script install.

**Comment by ghost** [comment]
I was running this in a vm. After each test, I reverted to clean snapshot. On my next run I will look for it there.

Thanks

**Comment by JMSDOnline** [comment]
I see. I am going to stay in tonight and run a few trials. I may have letsencypt functions coded in and available as soon as tomorrow afternoon. Pretty sure I left some quotes out on the ssl function so it was not renaming the cert within the `yoursite.conf`.

**Comment by ghost** [comment]
I just ran the dev installer and the keys are created and placed in /srv/www/no/ssl/

```
root@testbox:~# ll /srv/www/no/ssl/
-rw-r--r-- 1 root www-data 1229 Apr 30 10:35 no.crt
-rw-r--r-- 1 root www-data 1704 Apr 30 10:35 no.key
```

and it appears that the /etc/nginx/conf.d/yoursite.conf is either not renamed or not created

```
root@testbox:~# ll /etc/nginx/conf.d/
-rw-r--r-- 1 root root 2502 Apr 29 18:12 default.conf.save
-rw-r--r-- 1 root root 2557 Apr 29 17:58 default.php7.conf.save
-rw-r--r-- 1 root root 2754 Apr 30 10:35 no.conf
```

I hope this helps and look forward to letsencrypt.

Thanks

**Comment by JMSDOnline** [comment]
That does help, I thank you for the feedback.

I am working on letsencrypt once I sort out a couple of minor issues. Later today or tomorrow we should see it as part of the script.

As per the `/etc/nginx/conf.d/yoursite.conf` it should be renamed to the `/etc/nginx/conf.d/no.conf`

**Comment by iamkingsleyf** [comment]
is this fix?

**Comment by JMSDOnline** [comment]
> is this fix?

Use certbot. I haven't implemented the certificate function and when I do, it will more than likely use .acme. For now, certbot is the easiest less intrusive method.

https://certbot.eff.org/all-instructions/#ubuntu-16-04-xenial-nginx
