### ISSUE TITLE
Install Failed

### ISSUE THREAD

**Issue by anikitin35** [JMSDOnline/vstacklet#91]
`Visit http://168.235.147.194/checkinfo.php to verify your install.
Remember to remove the checkinfo.php file after verification.

INSTALLATION COMPLETED in 31/min

root@ubuntu:~#
root@ubuntu:~# Do you want to generate an SSL cert and configure HTTPS? (Y/n): Y
-bash: syntax error near unexpected token `('
root@ubuntu:~# Generating a 2048 bit RSA private key
Generating: command not found
root@ubuntu:~# ........................................................................................................................................................................................................................................................................................................................................................................+++
........................................................................................................................................................................................................................................................................................................................................................................+++: command not found
root@ubuntu:~# ................................................................................+++
................................................................................+++: command not found
root@ubuntu:~# writing new private key to '/srv/www/allvologda/ssl/allvologda.key'
writing: command not found
root@ubuntu:~# -----
-----: command not found
root@ubuntu:~# You are about to be asked to enter information that will be incorporated
You: command not found
root@ubuntu:~# into your certificate request.
No command 'into' found, did you mean:
 Command 'info' from package 'info' (main)
 Command 'pinto' from package 'pinto' (universe)
into: command not found
root@ubuntu:~# What you are about to enter is what is called a Distinguished Name or a DN.
No command 'What' found, did you mean:
 Command 'jhat' from package 'openjdk-7-jdk' (main)
 Command 'jhat' from package 'openjdk-6-jdk' (universe)
 Command 'chat' from package 'ppp' (main)
What: command not found
root@ubuntu:~# There are quite a few fields but you can leave some blank
There: command not found
root@ubuntu:~# For some fields there will be a default value,
No command 'For' found, did you mean:
 Command 'sor' from package 'pccts' (universe)
 Command 'vor' from package 'vor' (universe)
 Command 'tor' from package 'tor' (universe)
For: command not found
root@ubuntu:~# If you enter '.', the field will be left blank.
If: command not found
root@ubuntu:~# -----
-----: command not found
root@ubuntu:~# Country Name (2 letter code) [AU]:RU
-bash: syntax error near unexpected token`('
root@ubuntu:~# State or Province Name (full name) [Some-State]:Vologda
-bash: syntax error near unexpected token `('
root@ubuntu:~# Locality Name (eg, city) []:Vologda
-bash: syntax error near unexpected token`('
root@ubuntu:~# Organization Name (eg, company) [Internet Widgits Pty Ltd]:Nikitin Alexey Vladimirovich
-bash: syntax error near unexpected token `('
root@ubuntu:~# Organizational Unit Name (eg, section) []Private Entrepreneur                                                     Common Name (e.g. server FQDN or YOUR name) []:Nikitin Alexey Vladimirovich
-bash: syntax error near unexpected token`('
root@ubuntu:~# Email Address []:anikitin35@gmail.com
No command 'Email' found, did you mean:
 Command 'wmail' from package 'wmail' (universe)
 Command 'mail' from package 'mailutils' (universe)
 Command 'tmail' from package 'uw-mailutils' (universe)
 Command 'kmail' from package 'kmail' (universe)
 Command 'dmail' from package 'uw-mailutils' (universe)
 Command 'cmail' from package 'xboard' (universe)
 Command 'rmail' from package 'courier-mta' (universe)
 Command 'rmail' from package 'postfix' (main)
 Command 'rmail' from package 'exim4-daemon-heavy' (main)
 Command 'rmail' from package 'exim4-daemon-light' (main)
 Command 'rmail' from package 'masqmail' (universe)
 Command 'rmail' from package 'rmail' (universe)
Email: command not found
root@ubuntu:~# chmod: cannot access ‘/etc/ssl/private/allvologda.key’: No such file or directory
No command 'chmod:' found, did you mean:
 Command 'chmod' from package 'coreutils' (main)
chmod:: command not found
root@ubuntu:~#
root@ubuntu:~# Do you want to generate an SSL cert and configure HTTPS? (Y/n): Y
-bash: syntax error near unexpected token `('
root@ubuntu:~# Generating a 2048 bit RSA private key
Generating: command not found
`

My ip/checkinfo.php

Error 503 Backend fetch failed

Backend fetch failed

Guru Meditation:

XID: 65545

Varnish cache server

**Comment by JMSDOnline** [comment]
SSL install is to be replaced in regards to Lets Encrypt support. All the current ssl install does is a sample self-signed ssl cert (which is deprecated) Select **N** on SSL creation for now. 

Also, what ubuntu Release are you attempting this on? I have not encountered your other issue #92 in over 200 server installs.

Please provide more information so my support shot is not so broad.
