### ISSUE TITLE
Line 671 error

### ISSUE THREAD

**Issue by anikitin35** [JMSDOnline/vstacklet#92]
`Do you want to install phpMyAdmin? (Y/n): Y
vstacklet/vstacklet-ubuntu-stack.sh: line 671: mysqladmin: command not found
`

**Comment by JMSDOnline** [comment]
This would likely only happen if your dependencies failed to install. I assume you are attempting this with php5 selected as (**Y**).? phpmyadmin support is now functional with php7 and I would advise you try an install with 7 in mind. I will soon be deprecating php5.6.
