### ISSUE TITLE
Changed CSF URL

### ISSUE THREAD

**Issue by thezelja** [JMSDOnline/vstacklet#94]
CSF URL changed.
New URL: [https://download.configserver.com/csf.tgz](https://download.configserver.com/csf.tgz)

Files Affected:
[https://github.com/JMSDOnline/vstacklet/blob/master/vstacklet-ubuntu-stack.sh#L741](https://github.com/JMSDOnline/vstacklet/blob/master/vstacklet-ubuntu-stack.sh#L741)

**Comment by JMSDOnline** [comment]
Thanks for the heads up @thezelja :+1:
