### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by iamkingsleyf** [JMSDOnline/vstacklet#96]
Hello;

Nice script giving it a test.... i have few questions.

1. How is mariadb, nginx, etc being updated?
2. Can i use this for multiple site?
3. i thought memcache is not compatitable with php7
4. Support for PHP7.1?

**Comment by JMSDOnline** [comment]
1. You update them via the normal process of apt update/upgrade. These are apt sources and are handled via system updates, the script does nothing more than install the stack and implement your first domain/directory.
2. You can. You need to create separate .conf files per the site/directory you are wanting to handle.
3. Not sure why you would think that, it is. 😄 
4. You can update to php7.1 at any time. I don't have plans to implement this yet as we have another 2 years to run the LTS of php7.0

**Comment by iamkingsleyf** [comment]
alright thanks.. will wait for the ssl feature. really don't understand this https://certbot.eff.org/all-instructions/#ubuntu-16-04-xenial-nginx
